### ISSUE TITLE
Any chance of future linux support?

### ISSUE THREAD

**Issue by duodecillian** [libgenapps/LibgenDesktop#8] opened 2019-08-22 01:44 UTC

**Comment by libgenapps** [comment] 2019-08-23 00:01
Duplicate of https://github.com/libgenapps/LibgenDesktop/issues/5.

The code base is about 80-90 percent Windows-specific so adding Linux support is almost the same as writing a new app.

As a matter of fact, there is a web app currently being developed that may potentially have Linux support in the future: https://github.com/libgenapps/LibgenServer.

**Closed by libgenapps** 2019-08-23 00:01 UTC
Labels: duplicate
