### ISSUE TITLE
请问软件内置的下载器的 自动清理 功能是什么？

### ISSUE THREAD

**Issue by lyricofgod** [libgenapps/LibgenDesktop#21] opened 2020-03-17 02:45 UTC
优秀的工具！但是内置下载器存在如下问题：
批量下载时，已经完成下载的项目，在下一次启动libgen desktop 之后，默认为全部停止，如果选择全部启动，则已经下载的文件会被重新下载一次，有些文件会自动在文件名上添加（1,2..n）重命名再保存一次。有的则提示重命名失败，下载到了100%之后进度条变红。
如上问题对于批量下载多个文件应用时，用户体验不佳。需要人工鉴别哪些文件已经下载过，然后手工停止相关的下载任务。请问，在下一版的升级中，可否修正这个问题？
有一个 自动清理按钮，但是不知道具体用途，好像没看到相应的帮助文档。如果选择自动清理，是否会清除已完成的任务，还是连文件一并清除？还是清理出错的任务？还是清除死链接？  麻烦开发者看到回复一下，谢谢！

**Comment by libgenapps** [comment] 2020-03-17 21:00
"REMOVE COMPLETED" button should remove only successfully downloaded items from the list. It doesn't remove the files. In the same way, "START ALL" button should start only the stopped downloads and should not affect completed ones.

The status of download items should be preserved between runs (i.e. if a file was downloading before closing the app, it should resume the download after next start of the app). I'll check if all of this still works.

**Comment by libgenapps** [comment] 2020-05-11 00:07
Indeed there was a race condition bug causing statuses of all download items to change sometimes to "Stopped" if you are closing the app when download is active. This was fixed in 1.4.0. I couldn't reproduce other issues mentioned in your message but I suspect that they could be the side effects of the first issue. Please check this again with 1.4.0 and post another message if you still experience them.

**Closed by libgenapps** 2020-05-11 00:07 UTC
