### ISSUE TITLE
Do you have a version for MacOS? 

### ISSUE THREAD

**Issue by magshaban** [libgenapps/LibgenDesktop#23] opened 2020-04-19 17:08 UTC
Do you have a version for MacOS?

**Comment by libgenapps** [comment] 2020-05-01 02:46
Duplicate of https://github.com/libgenapps/LibgenDesktop/issues/5, https://github.com/libgenapps/LibgenDesktop/issues/8, https://github.com/libgenapps/LibgenDesktop/issues/9, and https://github.com/libgenapps/LibgenDesktop/issues/20.

**Closed by libgenapps** 2020-05-01 02:46 UTC
Labels: duplicate
